---
- name: rproxy setup
  hosts: rproxy

  tasks:
    - name: ensure apache is at the latest version
      apt: name=apache2 state=latest
      sudo: yes

    - name: ensure apache is running (and enable it at boot)
      service: name=apache2 state=started enabled=yes
      sudo: yes


- name: appserver setup
  hosts: appservers

  tasks:
    - name: ensure tomcat7 is at latest version
      apt: name=tomcat7 state=latest
      sudo: yes

    - name: ensure tomcat7 is running (and enable it at boot)
      service: name=tomcat7 state=started enabled=yes
      sudo: yes
